name: Update File with API Data

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Data from API
        run: |
          API_DATA=$(curl -s "https://www.udemy.com/api-2.0/courses/4460762/?fields%5Bcourse%5D=num_subscribers")
          echo "API Data: $API_DATA"
          CSV_DATA=$(echo "$API_DATA" | jq -r '.num_subscribers')
          echo "CSV Data: $CSV_DATA"
          echo "$CSV_DATA" > api_data.csv

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update data from API"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
